---
- name: ensure db_dumps folder
  file:
    path: "{{ db_path }}"
    state: directory

- name: "dump database"
  mysql_db:
    state: dump
    name: "{{ mysql_database }}"
    login_host: 127.0.0.1
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_port: "{{ mysql_port }}"
    target: "{{ db_path }}/{{ db_dumpfile }}"

- name: Compress the database dump
  archive: 
    path: "{{ db_path }}/{{ db_dumpfile }}"
    format: gz
