# This is for docker on development and production, not
# Docker for Mac (development)
# This configuration assumes that the developer has
# Docker for Mac installed.

docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_install_compose: true
docker_compose_version: "1.18.0"
docker_compose_path: /usr/local/bin/docker-compose
